# Generated by Django 2.0.2 on 2018-03-21 20:55

import data_import.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondingAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(max_length=1000, null=True, upload_to=data_import.models.upload_name)),
                ('reporting_year', models.IntegerField()),
                ('reporting_period_start_date', models.DateField()),
                ('reporting_period_end_date', models.DateField()),
                ('response_date', models.DateField()),
                ('google_drive_file_id', models.CharField(max_length=255)),
                ('responding_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.RespondingAgency')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(data_import.models.set_deleted_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='data_import.Upload'),
        ),
    ]
