# Generated by Django 2.0.2 on 2018-03-24 13:04

import data_import.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standardized_file', models.FileField(max_length=1000, null=True, upload_to=data_import.models.standardized_file_upload_name)),
                ('reporting_year', models.IntegerField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standardized_files', to='data_import.Upload')),
            ],
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='data_import.Upload'),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='standardized_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_files', to='data_import.StandardizedFile'),
        ),
        migrations.RunSQL('CREATE EXTENSION pgcrypto'),
    ]
