# Generated by Django 2.0.2 on 2018-04-23 20:26

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_add_standardizedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizedfile',
            name='status',
            field=django_fsm.FSMField(default='uploaded', max_length=50),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_file', to='data_import.Upload'),
        ),
        migrations.AlterField(
            model_name='standardizedfile',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standardized_file', to='data_import.Upload'),
        ),
    ]
