# Generated by Django 2.0.2 on 2018-04-18 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_add_standardizedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizedfile',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('imported', 'Imported')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_file', to='data_import.Upload'),
        ),
        migrations.AlterField(
            model_name='standardizedfile',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standardized_file', to='data_import.Upload'),
        ),
        migrations.RunSQL('''
            ALTER TABLE data_import_standardizedfile
              ADD CONSTRAINT check_status
              CHECK (status = 'uploaded' OR status = 'imported')
        ''', reverse_sql='''
            ALTER TABLE data_import_standardizedfile
              DROP CONSTRAINT check_status
        '''),
    ]
