# Generated by Django 2.0.2 on 2018-07-26 18:22

import data_import.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_add_standardizedfile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcefile',
            name='google_drive_file_id',
        ),
        migrations.AddField(
            model_name='standardizedfile',
            name='responding_agency',
            field=models.ManyToManyField(related_name='responding_agencies', to='data_import.RespondingAgency'),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='response_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='source_file',
            field=models.FileField(max_length=1000, upload_to=data_import.models.source_file_upload_name),
        ),
    ]
