# Generated by Django 2.0.2 on 2018-07-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0004_adjust_file_mgmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='reporting_period_end_date',
            field=models.DateField(blank=True, help_text='Leave blank for Dec. 31 of reporting year'),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='reporting_period_start_date',
            field=models.DateField(blank=True, help_text='Leave blank for Jan. 1 of reporting year'),
        ),
    ]
