# Generated by Django 2.0.2 on 2018-10-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_blankable_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcefile',
            name='standardized_file',
        ),
    ]
