# Generated by Django 2.2.9 on 2020-03-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0007_alias_base_class'),
    ]

    operations = [
        migrations.RunSQL('''
            INSERT INTO data_import_respondingagencyalias (responding_agency_id, name, preferred)
              SELECT id, name, TRUE
              FROM data_import_respondingagency
        '''),
    ]
