# Generated by Django 2.0.2 on 2018-02-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20180215_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
