# Generated by Django 2.0.2 on 2018-04-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_person_slug'),
    ]

    operations = [
        migrations.RunSQL('DROP INDEX IF EXISTS payroll_employer_btrim_parent_id_idx'),
        migrations.RunSQL('DROP INDEX IF EXISTS payroll_employer_btrim_idx'),
        migrations.RunSQL('DROP INDEX IF EXISTS payroll_position_btrim_employer_id_idx'),
        migrations.RunSQL('CREATE UNIQUE INDEX ON payroll_employer (TRIM(name), parent_id)'),
        migrations.RunSQL('CREATE UNIQUE INDEX ON payroll_employer (TRIM(name)) WHERE parent_id IS NULL'),
        migrations.RunSQL('CREATE UNIQUE INDEX ON payroll_position (TRIM(title), employer_id)'),
    ]
