# Generated by Django 2.0.2 on 2018-04-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    '''
    n.b. The defaults in this migration were one-off defaults to
    migrate existing data; they do not exist at the database level.
    '''
    dependencies = [
        ('payroll', '0006_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='vintage',
            field=models.PositiveIntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='vintage',
            field=models.PositiveIntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='vintage',
            field=models.PositiveIntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='vintage',
            field=models.PositiveIntegerField(),
        ),
    ]
