# Generated by Django 2.0.2 on 2018-04-09 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_add_standardizedfile'),
        ('payroll', '0007_slug_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.Upload'),
        ),
        migrations.AddField(
            model_name='person',
            name='vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.Upload'),
        ),
        migrations.AddField(
            model_name='position',
            name='vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.Upload'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.Upload'),
        ),
    ]
