# Generated by Django 2.0.2 on 2018-04-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_add_standardizedfile'),
        ('payroll', '0009_use_decimalfield_for_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='salaries',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='position',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='start_date',
        ),
        migrations.AddField(
            model_name='job',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='payroll.Person'),
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Position'),
        ),
        migrations.AddField(
            model_name='job',
            name='vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.Upload'),
        ),
        migrations.AddField(
            model_name='salary',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='payroll.Job'),
            preserve_default=False,
        ),
        migrations.RunSQL('CREATE UNIQUE INDEX ON payroll_job (person_id, position_id, start_date)'),
    ]
