# Generated by Django 2.0.2 on 2018-05-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_job'),
    ]

    operations = [
        migrations.RunSQL('CREATE UNIQUE INDEX ON payroll_employer (name) WHERE parent_id IS NULL'),
    ]
