# Generated by Django 2.0.2 on 2018-05-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_unique_index_redux'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=255)),
                ('chicago', models.BooleanField()),
                ('cook_or_collar', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='taxonomy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='payroll.EmployerTaxonomy'),
        ),
        migrations.RunSQL('''
            INSERT INTO payroll_employertaxonomy (entity_type, chicago, cook_or_collar)
              SELECT DISTINCT ON (entity_type, chicago, cook_or_collar)
                entity_type,
                chicago,
                cook_or_collar
              FROM employer_taxonomy
        ''', reverse_sql='DELETE FROM payroll_employertaxonomy'),
        migrations.RunSQL('''
            UPDATE payroll_employer
            SET taxonomy_id = model_taxonomy.id
            FROM employer_taxonomy AS raw_taxonomy
            JOIN payroll_employertaxonomy AS model_taxonomy
            USING (entity_type, chicago, cook_or_collar)
            WHERE TRIM(LOWER(payroll_employer.name)) = TRIM(LOWER(raw_taxonomy.entity))
              AND payroll_employer.parent_id IS NULL
        ''', reverse_sql='''
            UPDATE payroll_employer
            SET taxonomy_id = NULL
        ''')
    ]
