# Generated by Django 2.0.2 on 2018-05-30 16:53

from django.db import connection, migrations, models
import django.db.models.deletion


def import_default_taxonomy(*args):
    table_name = 'employer_taxonomy'

    columns = '''
        entity VARCHAR,
        entity_type VARCHAR,
        chicago BOOLEAN,
        cook_or_collar BOOLEAN
    '''

    create = 'CREATE TABLE {} ({})'.format(table_name, columns)

    with connection.cursor() as cursor:
        cursor.execute(create)

    with open('data/output/2018-05-30-employer_taxonomy.csv', 'r', encoding='utf-8') as f:
        with connection.cursor() as cursor:
            copy_fmt = 'COPY "{table}" ({cols}) FROM STDIN CSV HEADER'

            copy = copy_fmt.format(table=table_name,
                                   cols=columns.replace(' VARCHAR', '').replace(' BOOLEAN', ''))

            cursor.copy_expert(copy, f)


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_unique_index_redux'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=255)),
                ('chicago', models.BooleanField()),
                ('cook_or_collar', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='taxonomy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='payroll.EmployerTaxonomy'),
        ),
        migrations.RunPython(import_default_taxonomy),
        migrations.RunSQL('''
            INSERT INTO payroll_employertaxonomy (entity_type, chicago, cook_or_collar)
              SELECT DISTINCT ON (entity_type, chicago, cook_or_collar)
                entity_type,
                chicago,
                cook_or_collar
              FROM employer_taxonomy
        ''', reverse_sql='DELETE FROM payroll_employertaxonomy'),
        migrations.RunSQL('''
            UPDATE payroll_employer
            SET taxonomy_id = model_taxonomy.id
            FROM employer_taxonomy AS raw_taxonomy
            JOIN payroll_employertaxonomy AS model_taxonomy
            USING (entity_type, chicago, cook_or_collar)
            WHERE TRIM(LOWER(payroll_employer.name)) = TRIM(LOWER(raw_taxonomy.entity))
              AND payroll_employer.parent_id IS NULL
        ''', reverse_sql='''
            UPDATE payroll_employer
            SET taxonomy_id = NULL
        ''')
    ]
