# Generated by Django 2.0.2 on 2018-06-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_add_standardizedfile_status'),
        ('payroll', '0012_classify_employers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population', to='payroll.Employer')),
                ('vintage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.Upload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
