# Generated by Django 2.0.2 on 2018-06-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_classify_employers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
                ('population_year', models.IntegerField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population', to='payroll.Employer')),
            ],
        ),
    ]
