# Generated by Django 2.0.2 on 2018-07-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_add_employeruniverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='taxonomy',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='employers',
                to='payroll.EmployerTaxonomy'
            ),
        ),
        migrations.AlterField(
            model_name='employer',
            name='universe',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='employers',
                to='payroll.EmployerUniverse'
            ),
        ),
    ]
