# Generated by Django 2.0.2 on 2018-07-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_make_fields_blankable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employertaxonomy',
            options={'verbose_name_plural': 'Employer taxonomies'},
        ),
    ]
