# Generated by Django 2.0.2 on 2018-07-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_auto_20180712_1843'),
        ('payroll', '0018_auto_20180713_1710'),
    ]

    operations = [
    ]
