# Generated by Django 2.0.2 on 2018-07-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_merge_20180713_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('payroll.employer',),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('payroll.employer',),
        ),
    ]
