# Generated by Django 2.0.2 on 2018-07-27 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_blankable_dates'),
        ('payroll', '0020_meta_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitRespondingAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_year', models.IntegerField()),
                ('responding_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='data_import.RespondingAgency')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responding_agencies', to='payroll.Employer')),
            ],
        ),
    ]
