# Generated by Django 2.0.2 on 2018-09-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_add_unitrespondingagency'),
    ]

    operations = [
        migrations.RunSQL('''
            DROP TRIGGER person_slug ON payroll_person
        '''),
        migrations.RunSQL('''
            DROP TRIGGER employer_slug ON payroll_employer
        '''),
        migrations.RunSQL('''
            CREATE TRIGGER person_slug AFTER INSERT
            ON payroll_person FOR EACH ROW EXECUTE PROCEDURE
            person_slug_trigger()
        ''', reverse_sql='DROP TRIGGER person_slug ON payroll_person'),
        migrations.RunSQL('''
            CREATE TRIGGER employer_slug AFTER INSERT
            ON payroll_employer FOR EACH ROW EXECUTE PROCEDURE
            employer_slug_trigger()
        ''', reverse_sql='DROP TRIGGER employer_slug ON payroll_employer'),
    ]
