# Generated by Django 2.0.2 on 2018-09-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_revise_trigger'),
    ]

    operations = [
        migrations.RunSQL('''
            CREATE UNIQUE INDEX single_reporting_agency
            ON payroll_unitrespondingagency (
              reporting_year,
              responding_agency_id,
              unit_id
            )
        ''', reverse_sql='DROP INDEX single_reporting_agency')
    ]
