# Generated by Django 2.0.2 on 2019-04-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_add_person_noindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='person',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Check this box to prevent third-party search engines from capturing this person'),
        ),
    ]
