# Generated by Django 2.0.2 on 2019-10-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_add_noindex_helptext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userzipcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserZipcode',
        ),
    ]
