# Generated by Django 2.2.9 on 2020-02-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_removeuserzipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='extra_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.CheckConstraint(check=models.Q(('amount__isnull', False), ('extra_pay__isnull', False), _connector='OR'), name='total_pay_not_null'),
        ),
    ]
