# Generated by Django 2.2.9 on 2020-02-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_auto_20200205_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employer_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.RunSQL('''
            CREATE FUNCTION employer_id_trigger() RETURNS trigger AS '
                BEGIN
                  NEW.employer_id := COALESCE(NEW.parent_id, NEW.id);
                  RETURN NEW;
                END' LANGUAGE 'plpgsql'
        ''', reverse_sql='DROP FUNCTION employer_slug_trigger CASCADE'),
        migrations.RunSQL('''
            CREATE TRIGGER employer_id_trigger BEFORE INSERT OR UPDATE
            ON payroll_employer FOR EACH ROW EXECUTE PROCEDURE
            employer_id_trigger()
        ''', reverse_sql='DROP TRIGGER employer_id_trigger ON payroll_employer'),
    ]
