# Generated by Django 2.2.9 on 2020-03-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_migrate_existing_aliases'),
    ]

    operations = [
        migrations.RunSQL('DROP INDEX IF EXISTS payroll_employer_btrim_parent_id_idx', reverse_sql='SELECT 1'),
        migrations.RunSQL('DROP INDEX IF EXISTS payroll_employer_btrim_idx', reverse_sql='SELECT 1'),
        migrations.RunSQL('DROP INDEX IF EXISTS payroll_position_btrim_employer_id_idx', reverse_sql='SELECT 1'),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('title', 'employer_id'), name='unique_position'),
        ),
        migrations.AddConstraint(
            model_name='employer',
            constraint=models.UniqueConstraint(condition=models.Q(parent_id__isnull=True), fields=('name',), name='unique_unit_name'),
        ),
        migrations.AddConstraint(
            model_name='employer',
            constraint=models.UniqueConstraint(condition=models.Q(parent_id__isnull=False), fields=('name', 'parent_id'), name='unique_department_name'),
        ),
    ]
