# Generated by Django 2.2.9 on 2021-08-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_refactor_unique_indexes_to_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerHighestSalaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'payroll_employer_highest_salaries',
                'managed': False,
            },
        ),
    ]
