# Generated by Django 2.2.9 on 2021-08-27 15:48

from django.db import migrations
from extra_settings.models import Setting


def add_donate_banner_message(apps, schema_editor):
    donate_message_html = """<p class="lead"><strong>Dear BGA readers,</strong></p>
        <p>First, thanks very much for visiting our Salary Database site. We know hundreds of thousands of people use it throughout the year and find it useful.</p>
        <p><strong>But we need your help to keep this important source of information going.</strong> This database costs money and time to complete. We contract with outside organizations, and BGA staffers spend more than a year requesting, compiling, organizing and checking data from hundreds of government bodies across Illinois to bring this site to you for free. We don't run ads and we are a small nonprofit.</p>
        <p>If every person who visited this site gave us $1, we could complete our fundraising for the year right now. If you find this database valuable, please take just a few minutes to support it. Thank you.</p>
        <p class="text-center"><a class="btn btn-primary btn-lg" href="https://donate.bettergov.org" target="_blank">Please support this work today!</a></p>
        """
        
    donate_message = Setting(name='DONATE_MESSAGE',
                             value_type=Setting.TYPE_TEXT,
                             value_text=donate_message_html)
    
    donate_message.save()
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_employerhighestsalaries'),
    ]

    operations = [
        migrations.RunPython(add_donate_banner_message),
    ]
