# Generated by Django 2.2.9 on 2021-08-30 18:47
'''
Create aliases for employer name changes in the admin interface.
'''

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_add_salary_view'),
    ]

    operations = [
        migrations.RunSQL('''
            WITH for_alias AS (
                SELECT DISTINCT ON (employer.id)
                    employer.id AS employer_id,
                    employer.name AS name,
                    TRUE AS preferred
                FROM django_admin_log log
                JOIN payroll_employer employer
                ON log.object_id::INT = employer.id
                LEFT JOIN payroll_employeralias alias
                ON employer.id = alias.employer_id
                  AND employer.name = alias.name
                WHERE content_type_id = 9
                  AND change_message ILIKE '%name%'
                  AND alias.name IS NULL
            ), update AS (
                UPDATE payroll_employeralias existing
                SET preferred = false
                FROM for_alias update
                WHERE existing.employer_id = update.employer_id
            )
            INSERT INTO payroll_employeralias (
                employer_id,
                name,
                preferred
            )
            SELECT
                employer_id,
                name,
                preferred
            FROM for_alias
        ''', reverse_sql='SELECT 1')
    ]
