# Generated by Django 2.2.9 on 2025-06-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0035_reflect_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_year', models.IntegerField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Person')),
                ('search_name', models.CharField(default="dummy search name", max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployerSearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_year', models.IntegerField()),
                ('headcount', models.IntegerField()),
                ('expenditure', models.DecimalField(decimal_places=2, max_digits=100)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employer')),
                ('search_name', models.CharField(default="dummy search name", max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='personsearchindex',
            constraint=models.UniqueConstraint(fields=('instance', 'reporting_year'), name='unique_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='employersearchindex',
            constraint=models.UniqueConstraint(fields=('instance', 'reporting_year'), name='unique_employer_idx'),
        ),
    ]
