# Generated by Django 2.2.9 on 2025-06-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX search_employersearchindex_search_idx
            ON search_employersearchindex
            USING GIN (to_tsvector('english', search_name));
            """,
            reverse_sql="DROP INDEX search_employersearchindex_search_idx;"
        ),
        
        migrations.RunSQL(
            """
            CREATE INDEX search_personsearchindex_search_idx
            ON search_personsearchindex
            USING GIN (to_tsvector('english', search_name));
            """,
            reverse_sql="DROP INDEX search_personsearchindex_search_idx;"
        ),
        migrations.RunSQL(
            """
            CREATE INDEX search_employersearchindex_trigram_idx
            ON search_employersearchindex
            USING GIN (search_name gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX search_employersearchindex_trigram_idx;"
        ),
        migrations.RunSQL(
            """
            CREATE INDEX search_personsearchindex_trigram_idx
            ON search_personsearchindex
            USING GIN (search_name gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX search_personsearchindex_trigram_idx;"
        ),
    ]
