# Generated by Django 2.2.9 on 2025-06-10 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_reflect_aliases'),
        ('search', '0002_add_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsearchindex',
            name='employer',
            field=models.ForeignKey(default='temporary', on_delete=django.db.models.deletion.CASCADE, to='payroll.Employer', to_field='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personsearchindex',
            name='search_title',
            field=models.CharField(default='temporary', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personsearchindex',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
            preserve_default=False,
        ),
    ]
