# Generated by Django 2.2.9 on 2025-06-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20250610_2119'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX search_positionsearchindex_search_idx
            ON search_personsearchindex
            USING GIN (to_tsvector('english', search_title));
            """,
            reverse_sql="DROP INDEX search_positionsearchindex_search_idx;"
        ),
        migrations.RunSQL(
            """
            CREATE INDEX search_positionsearchindex_trigram_idx
            ON search_personsearchindex
            USING GIN (search_title gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX search_positionsearchindex_trigram_idx;"
        ),
    ]
